### ISSUE TITLE
Current monitor

### ISSUE THREAD

**Issue by SevereOverfl0w** [DelusionalLogic/dotfiles#1]
Sorry, me again!

It would be nice to filter using the current monitor for something like i3 workspaces which are allocated per-monitor.

Is there an environment variable of some kind with the "current" monitor being rendered? This is obviously a little more complex, as commands might need running twice, which might not be part of the current design.

Not sure if we have access to the index or actual monitor name either, which might change the design.

**Comment by DelusionalLogic** [comment]
I think you are posting this in the wrong place. But you are right. I've been thinking about how to do this.

Right now i imagine something like defining units to only draw on certain monitors. That way everything could parsed the same way, but just only be rendered to where it makes sense.

**Comment by SevereOverfl0w** [comment]
I'm a doofus, yes. I'll re-open on the bard repo.
